# Generated by Django 3.2.8 on 2021-10-30 18:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Washer_Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('washer_name', models.CharField(max_length=200, null=True)),
                ('washer_location', models.CharField(max_length=255, null=True)),
                ('long_w', models.DecimalField(decimal_places=2, max_digits=10)),
                ('lat_w', models.DecimalField(decimal_places=2, max_digits=10)),
                ('is_available', models.BooleanField(default=True)),
                ('washer_created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Washing_Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=255, null=True)),
                ('car_model', models.CharField(max_length=255, null=True)),
                ('customer_location', models.CharField(max_length=255, null=True)),
                ('long_c', models.DecimalField(decimal_places=2, max_digits=10)),
                ('lat_c', models.DecimalField(decimal_places=2, max_digits=10)),
                ('distance', models.DecimalField(decimal_places=2, max_digits=10)),
                ('order_created', models.DateTimeField(auto_now_add=True)),
                ('assigned_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='washingorder', to='carwashapp.washer_profile')),
            ],
        ),
    ]
