# Generated by Django 3.2.8 on 2021-10-30 18:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('carwashapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='washing_order',
            name='assigned_to',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='washingorder', to='carwashapp.washer_profile'),
        ),
    ]
